apiVersion: core.michaelhenkel/v1
kind: Task
metadata:
  name: build-vrouter-kernel
spec:
  tasks:
    build:
      env:
        GOPATH: /root/go
        #CCACHE_DIR: /mnt/builder/.cache/ccache
        GOCACHE: /mnt/builder/.cache/go-build
        GOPROXY: https://svl-artifactory.juniper.net/artifactory/api/go/go,direct
      vars:
        REPOPATH: /root/go/src/ssd-git.juniper.net/contrail/cn2
      cmds:
      - if [ ! -d "/mnt/builder/.cache/ccache" ]; then mkdir -p /mnt/builder/.cache/ccache; fi
      - if [ ! -d "{{ .REPOPATH }}" ]; then mkdir -p {{ .REPOPATH }}; fi
      #- if [ ! -d "/mnt/builder/${PodNamespace}/${Plan}/build" ]; then mkdir -p /mnt/builder/${PodNamespace}/${Plan}/build; fi
      - cp /mnt/builder/${PodNamespace}/${Plan}/${Branch}/archive.tar.gz /archive.tar.gz
      - tar -C {{ .REPOPATH }} --strip-components 1 -zxf /archive.tar.gz
      - if [ ! -d "/mnt/builder/${PodNamespace}/${Plan}/${Branch}/out" ]; then mkdir -p /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out; fi
      - if [ ! -L "/tf-dev-env/tools" ]; then ln -s {{ .REPOPATH }}/tools /tf-dev-env/tools; fi
      - if [ ! -d "/tf-dev-env/vrouter" ]; then cp -r {{ .REPOPATH }}/vrouter /tf-dev-env/vrouter; fi
      - if [ ! -L "/tf-dev-env/src" ]; then ln -s {{ .REPOPATH }}/src /tf-dev-env/src; fi
      - if [ ! -L "/tf-dev-env/SConstruct" ]; then ln -s {{ .REPOPATH }}/SConstruct /tf-dev-env/SConstruct; fi
      - if [ ! -L "/tf-dev-env/controller" ]; then ln -s {{ .REPOPATH }}/tools/controller /tf-dev-env/controller; fi
      - cp -r /tf-dev-env/third_party/* {{ .REPOPATH }}/third_party/
      - if [ ! -L "/root/go/pkg" ]; then ln -s /mnt/builder/${PodNamespace}/${Plan}/pkg /root/go/pkg; fi
      - cd {{ .REPOPATH }}/build/kernel_downloader && /usr/local/go/bin/go build -o /kernel-downloader main.go
      - /kernel-downloader -config {{ .REPOPATH }}/build/kernel_downloader/kernellist.yaml -format table -loglevel debug -format yaml,/mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/kernels.yaml
      - cp -r /kernelmodules /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out
  container:
    name: build-vrouter-kernel
    image: registry.default.svc.cluster1.local:5000/c-builder:latest
    #command: ["sh","-c","while true;do sleep 10;done"]
    command: ["sh","-c","cp /var/task/task /mnt/builder/${PodNamespace}/${Plan}/vrouter-kernel-task.yaml; task -t /mnt/builder/${PodNamespace}/${Plan}/vrouter-kernel-task.yaml build"]
    resources:
      requests:
        cpu: "20"