# permissions for end users to edit tasktemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tasktemplate-editor-role
rules:
- apiGroups:
  - core.michaelhenkel
  resources:
  - tasktemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.michaelhenkel
  resources:
  - tasktemplates/status
  verbs:
  - get
