# permissions for end users to view tasktemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tasktemplate-viewer-role
rules:
- apiGroups:
  - core.michaelhenkel
  resources:
  - tasktemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.michaelhenkel
  resources:
  - tasktemplates/status
  verbs:
  - get
