apiVersion: core.michaelhenkel/v1
kind: Plan
metadata:
  name: test-plan
spec:
  stages:
    pullCode:
      taskReferences:
      - name: pull-cn2
        kind: Task
    build:
      taskReferences:
      - name: build-apiserver
        kind: Task   
  volume:
    name: builder
    glusterfs:
      endpoints: glusterfs-cluster
      path: builder