apiVersion: core.michaelhenkel/v1
kind: Task
metadata:
  name: pull-cn2
spec:
  tasks:
    gitClone:
      cmds:
      - cmd: echo "hello" > output.txt
      generates:
      - output.txt
  container:
    name: pull-cn2
    image: busybox:latest
    command: ["sh", "-c", "until cat /tmp/bla; do sleep 10;done"]
  


