apiVersion: core.michaelhenkel/v1
kind: Plan
metadata:
  name: test-plan
spec:
  stages:
  - name: stage1
    taskReferences:
    - name: task1stage1
      kind: Task
    - name: task2stage1
      kind: Task
  - name: stage2
    taskReferences:
    - name: task1stage2
      kind: Task   
  volume:
    name: builder
    glusterfs:
      endpoints: glusterfs-cluster
      path: builder