apiVersion: core.michaelhenkel/v1
kind: Task
metadata:
  name: pull-cn2
spec:
  tasks:
    clone:
      cmds:
      - cmd: mkdir -p /mnt/builder/${PodNamespace}/${Plan}/src/ssd-git.juniper.net/contrail
      - cmd: git clone https://gitlab-ci-token:Ldp61SNTg5qTtYNkSazj@ssd-git.juniper.net/contrail/cn2.git /mnt/builder/${PodNamespace}/${Plan}/src/ssd-git.juniper.net/contrail/cn2 
  container:
    name: pull-cn2
    image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/tasker
    command: ["task", "-t", "clone"]
  


