apiVersion: core.michaelhenkel/v1
kind: TaskTemplate
metadata:
  name: task5
spec:
  tasks:
    build:
      env:
        GOPATH: /root/go
        GOCACHE: /mnt/builder/.cache/go-build
      vars:
        REPOPATH: /root/go/src/ssd-git.juniper.net/contrail/cn2
        GOPROXY: https://svl-artifactory.juniper.net/artifactory/api/go/go,direct
      cmds:
      - "{{ .KERNEL }}"
      - "{{ .GCC }}"
      sources:
      - "{{ .REPOPATH }}/contrail/**/*.go"
      generates:
      - /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/contrail-k8s-apiserver
  container:
    name: build-apiserver
    image: registry.default.svc.cluster1.local:5000/tasker
    #command: ["sh","-c","cp /var/task/task /mnt/builder/${PodNamespace}/${Plan}/apiserver-task.yaml; task -t /mnt/builder/${PodNamespace}/${Plan}/apiserver-task.yaml build"]
    command: ["sh","-c","until cat /tmp/bla;do sleep 10;done"]


