apiVersion: core.michaelhenkel/v1
kind: TaskTemplate
metadata:
  name: build-vrouter-agent
spec:
  tasks:
    prep:
      env:
        GOPATH: /root/go
        CCACHE_DIR: /mnt/buildcache/.cache/ccache
        BUILDPATH: /mnt/buildcache/build
        GOCACHE: /mnt/builder/.cache/go-build
        GOPROXY: https://svl-artifactory.juniper.net/artifactory/api/go/go,direct
        GOPKGCACHE: /mnt/buildcache/pkg
        REPOPATH: /root/go/src/ssd-git.juniper.net/contrail/cn2
      cmds:
      - if [ ! -d "${CCACHE_DIR}" ]; then mkdir -p ${CCACHE_DIR}; fi
      - if [ ! -d "${GOCACHE}" ]; then mkdir -p ${GOCACHE}; fi
      - if [ ! -d "${GOPKGCACHE}" ]; then mkdir -p ${GOPKGCACHE}; fi
      - if [ ! -d "${BUILDPATH}" ]; then mkdir -p ${BUILDPATH}; fi
      - if [ ! -d "${REPOPATH}" ]; then mkdir -p ${REPOPATH}; fi
      - if [ ! -d "/mnt/builder/${PodNamespace}/${Plan}/build" ]; then mkdir -p /mnt/builder/${PodNamespace}/${Plan}/build; fi
      - cp /mnt/builder/${PodNamespace}/${Plan}/${Branch}/archive.tar.gz /archive.tar.gz
      - tar -C ${REPOPATH} --strip-components 1 -zxf /archive.tar.gz
      - if [ ! -d "/mnt/builder/${PodNamespace}/${Plan}/${Branch}/out" ]; then mkdir -p /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out; fi
      - ln -s ${GOPKGCACHE} /root/go/pkg
    agent:
      env:
        GOPATH: /root/go
        CCACHE_DIR: /mnt/buildcache/.cache/ccache
        BUILDPATH: /mnt/buildcache/build
        GOCACHE: /mnt/builder/.cache/go-build
        GOPROXY: https://svl-artifactory.juniper.net/artifactory/api/go/go,direct
        GOPKGCACHE: /mnt/buildcache/pkg
        REPOPATH: /root/go/src/ssd-git.juniper.net/contrail/cn2
      cmds:
      - cp -r /tf-dev-env/third_party/* ${REPOPATH}/third_party/
      - rm -rf ${REPOPATH}/build
      - if [ -n ${cpurequest} ]; then cpus="-j${cpurequest}"; fi
      - cd ${REPOPATH} && if [ -n ${cpurequest} ]; then cpus="-j${cpurequest}"; fi && scons --c++=c++11 --opt=production ${cpus} contrail-vrouter-agent
      - cd ${REPOPATH} && if [ -n ${cpurequest} ]; then cpus="-j${cpurequest}"; fi && scons --c++=c++11 --opt=production ${cpus} vrouter/utils
      - cp ${REPOPATH}/build/production/vnsw/agent/contrail/contrail-vrouter-agent /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/contrail-vrouter-agent
      - strip /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/contrail-vrouter-agent
      - for i in vif nh flow mpls mirror vxlan rt dropstats vrfstats vrinfo vrmemstats vrftable vrouter dpdkinfo dpdkconf qosmap; do cp ${REPOPATH}/build/production/vrouter/utils/${i} /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/${i}; strip /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/${i}; done
      sources:
      - "/tf-dev-env/**/*.cc"
      - "/tf-dev-env/**/*.c"
      - "/tf-dev-env/**/*.h"
      generates:
      - /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/contrail-vrouter-agent
    vroutergo:
      env:
        GOPATH: /root/go
        GOCACHE: /mnt/builder/.cache/go-build
        GOPROXY: https://svl-artifactory.juniper.net/artifactory/api/go/go,direct
        GOPKGCACHE: /mnt/buildcache/pkg
        REPOPATH: /root/go/src/ssd-git.juniper.net/contrail/cn2
      cmds:
      - cd ${REPOPATH}/vrouter-go && /usr/local/go/bin/go build -o /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/vrouter-go main.go
      sources:
      - "${REPOPATH}/vrouter-go/**/*.go"
      generates:
      - /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/vrouter-go
    dpdkdevbind:
      env:
        GOPATH: /root/go
        GOCACHE: /mnt/builder/.cache/go-build
        GOPROXY: https://svl-artifactory.juniper.net/artifactory/api/go/go,direct
        GOPKGCACHE: /mnt/buildcache/pkg
        REPOPATH: /root/go/src/ssd-git.juniper.net/contrail/cn2
      cmds:
      - cd ${REPOPATH}/dpdk-devbind && /usr/local/go/bin/go build -o /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/dpdk-devbind cmd/main.go
      sources:
      - "${REPOPATH}/dpdk-devbind/**/*.go"
      generates:
      - /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/dpdk-devbind
    supervisor:
      env:
        GOPATH: /root/go
        GOCACHE: /mnt/builder/.cache/go-build
        GOPROXY: https://svl-artifactory.juniper.net/artifactory/api/go/go,direct
        GOPKGCACHE: /mnt/buildcache/pkg
        REPOPATH: /root/go/src/ssd-git.juniper.net/contrail/cn2
      cmds:
      - cd ${REPOPATH}/vrouter-supervisor && /usr/local/go/bin/go mod tidy && /usr/local/go/bin/go build -o /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/vrouter-supervisor main.go
      sources:
      - "${REPOPATH}/vrouter-supervisor/**/*.go"
      generates:
      - /mnt/builder/${PodNamespace}/${Plan}/${Branch}/out/vrouter-supervisor
  container:
    name: build-vrouter-agent
    image: registry.default.svc.cluster1.local:5000/c-builder:latest
    #command: ["sh","-c","while true;do sleep 10;done"]
    command: ["sh","-c","cp /var/task/task /mnt/builder/${PodNamespace}/${Plan}/vrouter-agent-task.yaml; task -t /mnt/builder/${PodNamespace}/${Plan}/vrouter-agent-task.yaml prep agent vroutergo dpdkdevbind supervisor"]