apiVersion: core.michaelhenkel/v1
kind: TaskTemplate
metadata:
  name: pull-cn2
spec:
  tasks:
    clone:
      vars:
        ARCHIVE: /mnt/builder/${PodNamespace}/${Plan}/${Branch}/archive.tar.gz
      cmds:
      - if [ ! -d "/mnt/builder/${PodNamespace}/${Plan}/${Branch}" ]; then mkdir -p /mnt/builder/${PodNamespace}/${Plan}/${Branch}; fi
      - curl --header "PRIVATE-TOKEN:$(cat /var/token/token)" "https://ssd-git.juniper.net/api/v4/projects/contrail%2Fcn2/repository/archive?sha=${Branch}" -o {{ .ARCHIVE }}
      - if [ ! -d "/mnt/builder/${PodNamespace}/${Plan}/pkg" ]; then mkdir -p /mnt/builder/${PodNamespace}/${Plan}/pkg; fi
  container:
    name: pull-cn2
    image: registry.default.svc.cluster1.local:5000/tasker
    command: ["task", "-t","/var/task/task","clone"]
    #command: ["sh","-c","while true;do sleep 10;done"]